version: "3"
services:
  app:
    image: app:latest
    ports:
      - "80:80"
    restart: unless-stopped
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1